name: Build

on:
  push:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 17, 21, 24 ]
    name: Java ${{ matrix.java }} build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare version labels
        uses: k15g/action-version-labels@edge
        with:
          prefix: project

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
              
      - name: Build and deploy with Maven
        run: mvn --batch-mode --update-snapshots -P release-snapshot deploy
        if: matrix.java == 17
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Maven Build
        run: mvn --batch-mode --update-snapshots install
        if: matrix.java != 17

      - name: Docker login
        uses: docker/login-action@v3
        if: matrix.java == 17
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        if: matrix.java == 17
        run: make docker_build tag=dev

      - name: Push Snapshot images
        if: "matrix.java == 17 && !startsWith(github.ref, 'refs/tags/')"
        run: make docker_push tag=edge

      - name: Push Release images
        if: "matrix.java == 17 && startsWith(github.ref, 'refs/tags/')"
        run: |
          make docker_push tag=${{ env.PROJECT_VERSION }}
          make docker_push tag=latest
